# Generated by Django 4.1.7 on 2025-09-22 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FichaEntrevista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_entrevista', models.CharField(max_length=20)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('nombre_entrevistado', models.CharField(max_length=100)),
                ('run_entrevistado', models.CharField(max_length=12)),
                ('telefono_entrevistado', models.CharField(max_length=20)),
                ('domicilio_entrevistado', models.CharField(max_length=200)),
                ('correo_entrevistado', models.EmailField(max_length=254)),
                ('contenido_entrevista', models.TextField()),
                ('firma_entrevistado', models.CharField(max_length=100)),
                ('firma_entrevistador', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='FormularioDenuncia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_denunciante', models.CharField(max_length=100)),
                ('run_denunciante', models.CharField(max_length=12)),
                ('telefono_denunciante', models.CharField(max_length=20)),
                ('domicilio_denunciante', models.CharField(max_length=200)),
                ('correo_denunciante', models.EmailField(max_length=254)),
                ('nombre_estudiante', models.CharField(max_length=100)),
                ('curso_estudiante', models.CharField(max_length=50)),
                ('run_estudiante', models.CharField(max_length=12)),
                ('domicilio_estudiante', models.CharField(max_length=200)),
                ('nombre_denunciado', models.CharField(max_length=100)),
                ('curso_denunciado', models.CharField(blank=True, max_length=50)),
                ('rol', models.CharField(choices=[('Estudiante', 'Estudiante'), ('Apoderado', 'Apoderado'), ('Profesor Jefe', 'Profesor Jefe'), ('Profesor de Asignatura', 'Profesor de Asignatura'), ('Asistente', 'Asistente'), ('Otro', 'Otro')], max_length=30)),
                ('curso_denunciado_extra', models.CharField(blank=True, max_length=50)),
                ('asignatura', models.CharField(blank=True, max_length=100)),
                ('otro_rol', models.CharField(blank=True, max_length=100)),
                ('fecha_hora', models.CharField(max_length=100)),
                ('lugar', models.CharField(max_length=200)),
                ('testigos', models.TextField(blank=True)),
                ('descripcion', models.TextField()),
            ],
        ),
    ]
