# Generated by Django 5.2.6 on 2025-10-11 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protocolos', '0003_alter_actainvestigacion_acciones_realizadas_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Derivacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('derivaciones', models.CharField(help_text='Separar con coma si hay más de una. Ejemplo: constatar_lesiones,denuncia_delito', max_length=100)),
                ('fecha_lesiones', models.DateField(blank=True, null=True)),
                ('institucion_lesiones', models.CharField(blank=True, max_length=100)),
                ('funcionario_lesiones', models.CharField(blank=True, max_length=100)),
                ('firma_lesiones', models.CharField(blank=True, max_length=100)),
                ('respaldo_lesiones', models.FileField(blank=True, null=True, upload_to='derivaciones/')),
                ('fecha_delito', models.DateField(blank=True, null=True)),
                ('institucion_delito', models.CharField(blank=True, max_length=100)),
                ('funcionario_delito', models.CharField(blank=True, max_length=100)),
                ('firma_delito', models.CharField(blank=True, max_length=100)),
                ('respaldo_delito', models.FileField(blank=True, null=True, upload_to='derivaciones/')),
                ('fecha_tribunal', models.DateField(blank=True, null=True)),
                ('institucion_tribunal', models.CharField(blank=True, max_length=100)),
                ('funcionario_tribunal', models.CharField(blank=True, max_length=100)),
                ('firma_tribunal', models.CharField(blank=True, max_length=100)),
                ('respaldo_tribunal', models.FileField(blank=True, null=True, upload_to='derivaciones/')),
                ('tipo_medida_otras', models.CharField(blank=True, max_length=100)),
                ('descripcion_otras', models.TextField(blank=True)),
                ('funcionario_otras', models.CharField(blank=True, max_length=100)),
                ('firma_otras', models.CharField(blank=True, max_length=100)),
                ('respaldo_otras', models.FileField(blank=True, null=True, upload_to='derivaciones/')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='ActaInvestigacion',
        ),
    ]
