# Generated by Django 5.2.6 on 2025-10-11 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protocolos', '0004_derivacion_delete_actainvestigacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='derivacion',
            name='derivaciones',
            field=models.CharField(max_length=100),
        ),
    ]
