# Generated by Django 3.2.25 on 2025-10-18 01:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('protocolos', '0005_alter_derivacion_derivaciones'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoProtocolo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='apelacion',
            name='estado_informe',
            field=models.CharField(default='PENDIENTE', max_length=100),
        ),
        migrations.AddField(
            model_name='informeconcluyente',
            name='estado_informe',
            field=models.CharField(default='PENDIENTE', max_length=100),
        ),
        migrations.AddField(
            model_name='resolucionapelacion',
            name='estado_informe',
            field=models.CharField(default='PENDIENTE', max_length=100),
        ),
        migrations.CreateModel(
            name='Protocolo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(default='Pendiente', help_text='Ej: Pendiente, Resuelto, Vencido', max_length=50)),
                ('creador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='protocolos_creados', to=settings.AUTH_USER_MODEL)),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='protocolos', to='protocolos.tipoprotocolo')),
            ],
        ),
        migrations.AddField(
            model_name='derivacion',
            name='protocolo',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='protocolos.protocolo'),
        ),
        migrations.AddField(
            model_name='encuestabullying',
            name='protocolo',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='protocolos.protocolo'),
        ),
        migrations.AddField(
            model_name='fichaentrevista',
            name='protocolo',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='protocolos.protocolo'),
        ),
        migrations.AddField(
            model_name='formulariodenuncia',
            name='protocolo',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='protocolos.protocolo'),
        ),
        migrations.AlterField(
            model_name='apelacion',
            name='protocolo',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='protocolos.protocolo'),
        ),
        migrations.AlterField(
            model_name='informeconcluyente',
            name='protocolo',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='protocolos.protocolo'),
        ),
        migrations.AlterField(
            model_name='resolucionapelacion',
            name='protocolo',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='protocolos.protocolo'),
        ),
    ]
