# Generated by Django 5.2.6 on 2025-10-26 18:20

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protocolos', '0007_auto_20251017_2248'),
    ]

    operations = [
        migrations.AddField(
            model_name='encuestabullying',
            name='edad_estudiante',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='encuestabullying',
            name='fecha_encuesta',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='encuestabullying',
            name='genero_estudiante',
            field=models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro/No especifica')], max_length=1),
        ),
        migrations.AlterField(
            model_name='encuestabullying',
            name='comentario_adicional',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='encuestabullying',
            name='curso',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='encuestabullying',
            name='estudiante_iniciales',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='encuestabullying',
            name='protocolo',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='encuestabullying', to='protocolos.protocolo'),
        ),
        migrations.AlterField(
            model_name='formulariodenuncia',
            name='protocolo',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ficha_denuncia', to='protocolos.protocolo'),
        ),
    ]
