# Generated by Django 3.2.25 on 2025-10-28 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('protocolos', '0008_alter_formulariodenuncia_protocolo_and_more'),
        ('protocolos', '0008_encuestabullying_edad_estudiante_and_more'),
    ]

    operations = [
    ]
