# Generated by Django 3.2.25 on 2025-10-28 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protocolos', '0009_merge_20251028_1711'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='derivacion',
            name='protocolo',
        ),
        migrations.RemoveField(
            model_name='encuestabullying',
            name='protocolo',
        ),
        migrations.RemoveField(
            model_name='fichaentrevista',
            name='protocolo',
        ),
        migrations.RemoveField(
            model_name='formulariodenuncia',
            name='protocolo',
        ),
        migrations.RemoveField(
            model_name='informeconcluyente',
            name='protocolo',
        ),
        migrations.RemoveField(
            model_name='resolucionapelacion',
            name='protocolo',
        ),
        migrations.AlterModelOptions(
            name='tipoprotocolo',
            options={'ordering': ['orden']},
        ),
        migrations.AddField(
            model_name='tipoprotocolo',
            name='orden',
            field=models.PositiveIntegerField(default=0, help_text='Para ordenar la lista de protocolos'),
        ),
        migrations.AlterModelTable(
            name='protocolo',
            table='protocolo1_protocolo',
        ),
        migrations.DeleteModel(
            name='Apelacion',
        ),
        migrations.DeleteModel(
            name='Derivacion',
        ),
        migrations.DeleteModel(
            name='EncuestaBullying',
        ),
        migrations.DeleteModel(
            name='FichaEntrevista',
        ),
        migrations.DeleteModel(
            name='FormularioDenuncia',
        ),
        migrations.DeleteModel(
            name='InformeConcluyente',
        ),
        migrations.DeleteModel(
            name='ResolucionApelacion',
        ),
    ]
