# Generated by Django 3.2.25 on 2025-10-28 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('protocolos', '0010_auto_20251028_1853'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='tipoprotocolo',
            table='protocolo1_tipoprotocolo',
        ),
    ]
