# Generated by Django 3.2.25 on 2025-10-28 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('protocolos', '0011_alter_tipoprotocolo_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tipoprotocolo',
            options={},
        ),
        migrations.RemoveField(
            model_name='tipoprotocolo',
            name='orden',
        ),
    ]
