# Generated by Django 5.2.6 on 2025-10-08 18:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protocolo1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fichaentrevista',
            name='fecha',
        ),
        migrations.RemoveField(
            model_name='fichaentrevista',
            name='hora',
        ),
        migrations.AddField(
            model_name='fichaentrevista',
            name='fecha_hora',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
