# Generated by Django 5.2.6 on 2025-10-08 19:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protocolo1', '0002_remove_fichaentrevista_fecha_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actainvestigacion',
            name='acciones_realizadas',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='actainvestigacion',
            name='conclusiones',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='actainvestigacion',
            name='protocolo',
            field=models.CharField(default='PENDIENTE', max_length=100),
        ),
        migrations.AlterField(
            model_name='actainvestigacion',
            name='recomendaciones',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='actainvestigacion',
            name='responsable',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='actainvestigacion',
            name='tipificacion',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='apelacion',
            name='correo',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='apelacion',
            name='curso_o_cargo',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='apelacion',
            name='domicilio',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='apelacion',
            name='nombre_apelante',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='apelacion',
            name='protocolo',
            field=models.CharField(default='PENDIENTE', max_length=100),
        ),
        migrations.AlterField(
            model_name='apelacion',
            name='run_apelante',
            field=models.CharField(default='', max_length=12),
        ),
        migrations.AlterField(
            model_name='apelacion',
            name='texto_apelacion',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='encuestabullying',
            name='comentario_adicional',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='encuestabullying',
            name='curso',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='encuestabullying',
            name='estudiante_iniciales',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='formulariodenuncia',
            name='curso_denunciado',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='formulariodenuncia',
            name='descripcion',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='formulariodenuncia',
            name='lugar',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='formulariodenuncia',
            name='testigos',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='informeconcluyente',
            name='cargo_encargado',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='informeconcluyente',
            name='conclusiones',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='informeconcluyente',
            name='correo_encargado',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='informeconcluyente',
            name='curso_involucrado',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='informeconcluyente',
            name='descripcion_accion',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='informeconcluyente',
            name='descripcion_sancion',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='informeconcluyente',
            name='empresa_correos',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='informeconcluyente',
            name='fecha_citacion_afectado',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='informeconcluyente',
            name='fecha_citacion_denunciado',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='informeconcluyente',
            name='fecha_envio',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='informeconcluyente',
            name='fecha_inicio_medida',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='informeconcluyente',
            name='fecha_inicio_sancion',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='informeconcluyente',
            name='fecha_termino_medida',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='informeconcluyente',
            name='fecha_termino_sancion',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='informeconcluyente',
            name='firma_denunciado',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='informeconcluyente',
            name='firma_reclamante',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='informeconcluyente',
            name='hora_entrevista_afectado',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='informeconcluyente',
            name='hora_entrevista_denunciado',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='informeconcluyente',
            name='hora_envio',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='informeconcluyente',
            name='iniciales',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='informeconcluyente',
            name='lugar_entrevista_afectado',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='informeconcluyente',
            name='lugar_entrevista_denunciado',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='informeconcluyente',
            name='medio_citacion_afectado',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='informeconcluyente',
            name='medio_citacion_denunciado',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='informeconcluyente',
            name='nombre_encargado',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='informeconcluyente',
            name='nombre_firma_encargado',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='informeconcluyente',
            name='nombre_firma_remitente',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='informeconcluyente',
            name='protocolo',
            field=models.CharField(default='PENDIENTE', max_length=100),
        ),
        migrations.AlterField(
            model_name='informeconcluyente',
            name='run_encargado',
            field=models.CharField(default='', max_length=12),
        ),
        migrations.AlterField(
            model_name='informeconcluyente',
            name='sancion',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='informeconcluyente',
            name='tipo_accion',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='informeconcluyente',
            name='tipo_involucrado',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='resolucionapelacion',
            name='fundamentos',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='resolucionapelacion',
            name='medio_envio',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='resolucionapelacion',
            name='protocolo',
            field=models.CharField(default='PENDIENTE', max_length=100),
        ),
        migrations.AlterField(
            model_name='resolucionapelacion',
            name='rector_o_sostenedor',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='resolucionapelacion',
            name='resolucion',
            field=models.TextField(default=''),
        ),
    ]
