# Generated by Django 3.2.25 on 2025-10-18 01:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('protocolo1', '0006_auto_20251017_2208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apelacion',
            name='protocolo',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='protocolo1.protocolo'),
        ),
        migrations.AlterField(
            model_name='derivacion',
            name='protocolo',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='protocolo1.protocolo'),
        ),
        migrations.AlterField(
            model_name='encuestabullying',
            name='protocolo',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='protocolo1.protocolo'),
        ),
        migrations.AlterField(
            model_name='fichaentrevista',
            name='protocolo',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='protocolo1.protocolo'),
        ),
        migrations.AlterField(
            model_name='formulariodenuncia',
            name='protocolo',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='protocolo1.protocolo'),
        ),
        migrations.AlterField(
            model_name='informeconcluyente',
            name='protocolo',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='protocolo1.protocolo'),
        ),
        migrations.AlterField(
            model_name='resolucionapelacion',
            name='protocolo',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='protocolo1.protocolo'),
        ),
    ]
