# Generated by Django 4.2.25 on 2025-10-27 04:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('protocolo1', '0007_auto_20251017_2248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formulariodenuncia',
            name='protocolo',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ficha_denuncia', to='protocolo1.protocolo'),
        ),
        migrations.AlterField(
            model_name='protocolo',
            name='estado',
            field=models.CharField(default='En Creacion', help_text='Ej: En Creacion, Pendiente, Resuelto, Vencido', max_length=50),
        ),
    ]
