# Generated by Django 3.2.25 on 2025-10-28 23:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('protocolos', '0012_auto_20251028_1940'),
        ('formularios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiesgoSuicidaAnexo1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_afectado', models.CharField(max_length=255)),
                ('curso', models.CharField(max_length=100)),
                ('profesor_jefe', models.CharField(max_length=255)),
                ('apoderado', models.CharField(max_length=255)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('persona_detecta', models.CharField(max_length=255, verbose_name='Persona que detectó la situación')),
                ('relato_hechos', models.TextField(verbose_name='Relato de los hechos')),
                ('protocolo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='riesgo_suicida_anexo1', to='protocolos.protocolo')),
            ],
        ),
    ]
