# Generated by Django 5.2.6 on 2025-10-29 00:59

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formularios', '0002_riesgosuicidaanexo1'),
        ('protocolos', '0012_auto_20251028_1940'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiesgoSuicidaAnexo2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_derivacion', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de Derivación')),
                ('establecimiento_nombre', models.CharField(blank=True, max_length=255, verbose_name='Establecimiento Educacional')),
                ('profesional_deriva_nombre', models.CharField(max_length=255, verbose_name='Nombre del profesional que deriva')),
                ('profesional_deriva_cargo', models.CharField(max_length=150, verbose_name='Cargo del profesional que deriva')),
                ('profesional_deriva_email', models.EmailField(max_length=254, verbose_name='Correo electrónico del profesional que deriva')),
                ('profesional_deriva_telefono', models.CharField(max_length=50, verbose_name='Teléfono de contacto del profesional que deriva')),
                ('establecimiento_contacto_email', models.EmailField(blank=True, max_length=254, verbose_name='Correo electrónico de contacto con el Establecimiento')),
                ('establecimiento_contacto_telefono', models.CharField(blank=True, max_length=50, verbose_name='Teléfono de contacto con el Establecimiento')),
                ('estudiante_nombre', models.CharField(max_length=255, verbose_name='Nombre del Estudiante')),
                ('estudiante_run', models.CharField(max_length=12, verbose_name='RUN del Estudiante')),
                ('estudiante_fecha_nacimiento', models.DateField(verbose_name='Fecha de nacimiento del Estudiante')),
                ('estudiante_edad', models.PositiveSmallIntegerField(verbose_name='Edad del Estudiante')),
                ('estudiante_curso', models.CharField(max_length=100, verbose_name='Curso del Estudiante')),
                ('adulto_responsable_nombre', models.CharField(max_length=255, verbose_name='Adulto responsable o apoderado')),
                ('adulto_responsable_telefono', models.CharField(max_length=50, verbose_name='Teléfono de contacto del adulto responsable')),
                ('estudiante_direccion', models.CharField(max_length=300, verbose_name='Dirección del Estudiante')),
                ('motivo_derivacion', models.TextField(verbose_name='Motivos por el cual se deriva (indique el riesgo)')),
                ('acciones_efectuadas', models.TextField(verbose_name='Acciones efectuadas por el Establecimiento Educacional')),
                ('protocolo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='riesgo_suicida_anexo2', to='protocolos.protocolo')),
            ],
        ),
    ]
