# Generated by Django 5.2.6 on 2025-10-31 01:40

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formularios', '0003_riesgosuicidaanexo2'),
        ('protocolos', '0012_auto_20251028_1940'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiesgoSuicidaAnexo3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de Notificación')),
                ('hora', models.TimeField(verbose_name='Hora de Notificación')),
                ('establecimiento_nombre', models.CharField(blank=True, max_length=255, verbose_name='Establecimiento Educacional')),
                ('estudiante_nombre', models.CharField(blank=True, max_length=255, verbose_name='Nombre del Estudiante')),
                ('estudiante_curso', models.CharField(blank=True, max_length=100, verbose_name='Curso del Estudiante')),
                ('apoderado_nombre', models.CharField(max_length=255, verbose_name='Nombre del Adulto (Padre, madre o apoderado)')),
                ('apoderado_run', models.CharField(max_length=12, verbose_name='RUN del Apoderado')),
                ('acciones_a_seguir', models.TextField(verbose_name='Acciones a seguir por el apoderado')),
                ('nombre_firma_apoderado', models.CharField(max_length=255, verbose_name='Nombre y Firma del Apoderado')),
                ('nombre_firma_funcionario', models.CharField(max_length=255, verbose_name='Nombre y Firma de Funcionario')),
                ('cargo_funcionario', models.CharField(max_length=150, verbose_name='Cargo de Funcionario')),
                ('protocolo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='riesgo_suicida_anexo3', to='protocolos.protocolo')),
            ],
        ),
        migrations.CreateModel(
            name='RiesgoSuicidaAnexo4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de Reunión')),
                ('hora_inicio', models.TimeField(verbose_name='Hora de Inicio')),
                ('hora_termino', models.TimeField(verbose_name='Hora de Término')),
                ('lugar_reunion', models.CharField(max_length=255, verbose_name='Lugar de Reunión')),
                ('estudiante_nombre', models.CharField(blank=True, max_length=255, verbose_name='Nombre del Estudiante')),
                ('estudiante_curso', models.CharField(blank=True, max_length=100, verbose_name='Curso del Estudiante')),
                ('profesor_jefe', models.CharField(blank=True, max_length=255, verbose_name='Profesor Jefe')),
                ('asistentes', models.TextField(help_text='Liste un asistente por línea (Ej: Juan Pérez - Psicólogo)', verbose_name='Asistentes (Nombre, Cargo/Rol)')),
                ('puntos_tratados', models.TextField(verbose_name='Puntos Tratados')),
                ('acuerdos', models.TextField(verbose_name='Acuerdos y Compromisos')),
                ('proxima_reunion_fecha', models.DateField(blank=True, null=True, verbose_name='Fecha Próxima Reunión')),
                ('proxima_reunion_hora', models.TimeField(blank=True, null=True, verbose_name='Hora Próxima Reunión')),
                ('proxima_reunion_lugar', models.CharField(blank=True, max_length=255, verbose_name='Lugar Próxima Reunión')),
                ('firma_funcionario_establecimiento', models.CharField(max_length=255, verbose_name='Nombre y Firma Funcionario Establecimiento')),
                ('firma_profesional_salud', models.CharField(max_length=255, verbose_name='Nombre y Firma Profesional Equipo de Salud')),
                ('protocolo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='riesgo_suicida_anexo4', to='protocolos.protocolo')),
            ],
        ),
        migrations.CreateModel(
            name='RiesgoSuicidaAnexo5',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_derivacion', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de Derivación')),
                ('establecimiento_nombre', models.CharField(blank=True, help_text='Se autocompletará', max_length=255, verbose_name='Establecimiento Educacional')),
                ('establecimiento_direccion', models.CharField(blank=True, max_length=255, verbose_name='Dirección')),
                ('establecimiento_telefono', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('estudiante_nombre', models.CharField(blank=True, max_length=255, verbose_name='Nombre Completo del Estudiante')),
                ('estudiante_run', models.CharField(blank=True, max_length=12, verbose_name='RUN del Estudiante')),
                ('estudiante_fecha_nacimiento', models.DateField(blank=True, null=True, verbose_name='Fecha de Nacimiento')),
                ('estudiante_edad', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Edad')),
                ('estudiante_curso', models.CharField(blank=True, max_length=100, verbose_name='Curso')),
                ('motivo_derivacion', models.TextField(verbose_name='Motivo de Derivación')),
                ('acciones_entrevista_apoderado', models.TextField(blank=True, verbose_name='Entrevista con Apoderado (Resumen)')),
                ('acciones_coordinacion_salud', models.TextField(blank=True, verbose_name='Coordinación Equipo de Salud (Resumen)')),
                ('acciones_otras', models.TextField(blank=True, verbose_name='Otras acciones realizadas')),
                ('responsable_nombre', models.CharField(max_length=255, verbose_name='Nombre del Funcionario Responsable')),
                ('responsable_cargo', models.CharField(max_length=150, verbose_name='Cargo del Funcionario')),
                ('responsable_telefono', models.CharField(max_length=20, verbose_name='Teléfono de Contacto')),
                ('responsable_email', models.EmailField(max_length=254, verbose_name='Email de Contacto')),
                ('protocolo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='riesgo_suicida_anexo5', to='protocolos.protocolo')),
            ],
        ),
    ]
