# Generated by Django 4.2.25 on 2025-10-31 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('protocolos', '0012_auto_20251028_1940'),
        ('formularios', '0004_riesgosuicidaanexo3_riesgosuicidaanexo4_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReconocimientoIdentidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_legal', models.CharField(help_text='Nombre completo según documento de identidad', max_length=200)),
                ('rut_estudiante', models.CharField(help_text='RUT o N° de identificación del estudiante', max_length=20)),
                ('nombre_identitario', models.CharField(help_text='Nombre social con el que se identifica', max_length=200)),
                ('pronombres', models.CharField(help_text='Pronombres seleccionados o especificados', max_length=50)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('estado_solicitud', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Aplicado', 'Aplicado'), ('Rechazado', 'Rechazado')], default='Pendiente', max_length=20)),
                ('protocolo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reconocimiento_identidad', to='protocolos.protocolo')),
            ],
            options={
                'verbose_name': 'Solicitud de Reconocimiento de Identidad',
                'verbose_name_plural': 'Solicitudes de Reconocimiento de Identidad',
            },
        ),
        migrations.CreateModel(
            name='GestionReconocimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sistemas_actualizados', models.CharField(blank=True, help_text='Sistemas actualizados, separados por comas', max_length=255)),
                ('fecha_actualizacion', models.DateField()),
                ('comunicacion_estudiante', models.CharField(choices=[('Si', 'Sí'), ('No', 'No')], max_length=2)),
                ('observaciones', models.TextField(blank=True)),
                ('respaldo_gestion', models.FileField(blank=True, null=True, upload_to='reconocimiento_gestion/')),
                ('funcionario_responsable', models.CharField(max_length=255)),
                ('protocolo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gestion_reconocimiento', to='protocolos.protocolo')),
            ],
            options={
                'verbose_name': 'Gestión de Reconocimiento de Identidad',
                'verbose_name_plural': 'Gestiones de Reconocimiento de Identidad',
            },
        ),
    ]
