# Generated by Django 5.2.6 on 2025-11-01 01:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formularios', '0005_reconocimientoidentidad_gestionreconocimiento'),
        ('protocolos', '0012_auto_20251028_1940'),
    ]

    operations = [
        migrations.CreateModel(
            name='FichaAccidenteEscolar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estudiante_nombre', models.CharField(max_length=255, verbose_name='Nombre Estudiante')),
                ('estudiante_curso', models.CharField(max_length=100, verbose_name='Curso')),
                ('fecha_hora_accidente', models.DateTimeField(verbose_name='Fecha y Hora del Accidente')),
                ('descripcion_accidente', models.TextField(verbose_name='Describa el accidente escolar (Detección)')),
                ('primeros_auxilios', models.TextField(verbose_name='Acciones de Primeros Auxilios Realizadas')),
                ('aviso_apoderado_nombre', models.CharField(max_length=255, verbose_name='Nombre apoderado')),
                ('aviso_apoderado_medio', models.CharField(max_length=100, verbose_name='Medio de comunicación utilizado')),
                ('aviso_funcionario', models.CharField(max_length=255, verbose_name='Funcionario encargado de comunicarlo')),
                ('aislamiento_motivo', models.TextField(blank=True, verbose_name='Motivo del aislamiento')),
                ('aislamiento_funcionario', models.CharField(blank=True, max_length=255, verbose_name='Funcionario a cargo')),
                ('aislamiento_lugar', models.CharField(blank=True, max_length=255, verbose_name='Lugar aislado')),
                ('traslado_fecha_hora', models.DateTimeField(blank=True, null=True, verbose_name='Día y hora del traslado')),
                ('traslado_centro', models.CharField(blank=True, max_length=255, verbose_name='Centro al que fue trasladado')),
                ('traslado_funcionario', models.CharField(blank=True, max_length=255, verbose_name='Quién efectúa el traslado')),
                ('protocolo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ficha_accidente_escolar', to='protocolos.protocolo')),
            ],
        ),
    ]
