# Generated by Django 3.2.25 on 2025-11-01 21:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('protocolos', '0012_auto_20251028_1940'),
        ('formularios', '0006_fichaaccidenteescolar'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArmasAnexo1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_estudiante', models.CharField(max_length=255)),
                ('curso', models.CharField(max_length=100)),
                ('rut', models.CharField(max_length=12)),
                ('descripcion', models.TextField(verbose_name='Descripción de la situación')),
                ('protocolo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='anexo_armas', to='protocolos.protocolo')),
            ],
        ),
    ]
