# Generated by Django 3.2.25 on 2025-11-02 00:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('protocolos', '0012_auto_20251028_1940'),
        ('formularios', '0007_armasanexo1'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutolesionAnexo1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_estudiante', models.CharField(max_length=255, verbose_name='Nombre del Estudiante')),
                ('curso', models.CharField(max_length=100, verbose_name='Curso')),
                ('rut', models.CharField(max_length=12, verbose_name='RUT')),
                ('descripcion', models.TextField(verbose_name='Descripción de la situación')),
                ('protocolo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='anexo_autolesion', to='protocolos.protocolo')),
            ],
        ),
    ]
