# Generated by Django 3.2.25 on 2025-11-03 22:04

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('protocolos', '0012_auto_20251028_1940'),
        ('formularios', '0008_autolesionanexo1'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstudianteMadrePadreFicha2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_estudiante', models.CharField(max_length=255, verbose_name='Nombre Alumna/o')),
                ('curso', models.CharField(max_length=100, verbose_name='Curso')),
                ('fecha_informe_final', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha del informe final')),
                ('quien_elabora_informe', models.CharField(max_length=255, verbose_name='Quién elabora el informe')),
                ('funcionario_recibe_informe', models.CharField(max_length=255, verbose_name='Funcionario a quien se le entrega el informe')),
                ('fecha_cierre_protocolo', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha cierre de protocolo')),
                ('firma_funcionario_elabora', models.CharField(max_length=255, verbose_name='Nombre y firma del funcionario que elabora el informe')),
                ('firma_rector', models.CharField(max_length=255, verbose_name='Nombre y firma del Rector del Establecimiento')),
                ('protocolo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ficha2_madre_padre', to='protocolos.protocolo')),
            ],
        ),
        migrations.CreateModel(
            name='EstudianteMadrePadreFicha1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_entrevista', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de la entrevista')),
                ('individualizacion_apoderado', models.CharField(max_length=255, verbose_name='Individualización del apoderado')),
                ('motivo_entrevista', models.TextField(verbose_name='Motivo de la entrevista')),
                ('aspectos_relevantes', models.TextField(verbose_name='Aspectos relevantes de la entrevista')),
                ('nombre_firma_funcionario', models.CharField(max_length=255, verbose_name='Nombre y firma del funcionario que practica la entrevista')),
                ('nombre_firma_apoderado', models.CharField(max_length=255, verbose_name='Nombre y firma del apoderado')),
                ('protocolo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ficha1_madre_padre', to='protocolos.protocolo')),
            ],
        ),
        migrations.CreateModel(
            name='EstudianteMadrePadreFicha0',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_estudiante', models.CharField(max_length=255, verbose_name='Nombre Alumna/o')),
                ('curso', models.CharField(max_length=100, verbose_name='Curso')),
                ('fecha_citacion', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha en que se cita (Con fecha...)')),
                ('nombre_apoderado_citado', models.CharField(max_length=255, verbose_name='Se cita al apoderado...')),
                ('medio_citacion', models.CharField(max_length=150, verbose_name='A través de... (teléfono, agenda, etc.)')),
                ('fecha_concurrencia_citada', models.DateField(verbose_name='A fin de que concurra... (el día... de... del...)')),
                ('funcionario_que_cita', models.CharField(max_length=255, verbose_name='Nombre y firma del funcionario que cita')),
                ('nombre_apoderado_concurre', models.CharField(max_length=255, verbose_name='Nombre Apoderado (Yo...)')),
                ('rut_apoderado_concurre', models.CharField(max_length=12, verbose_name='Cédula nacional de identidad número...')),
                ('protocolo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ficha0_madre_padre', to='protocolos.protocolo')),
            ],
        ),
    ]
