# Generated by Django 4.2.25 on 2025-11-03 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formularios', '0008_autolesionanexo1'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reconocimientoidentidad',
            options={},
        ),
        migrations.RemoveField(
            model_name='reconocimientoidentidad',
            name='estado_solicitud',
        ),
        migrations.RemoveField(
            model_name='reconocimientoidentidad',
            name='fecha_solicitud',
        ),
        migrations.RemoveField(
            model_name='reconocimientoidentidad',
            name='nombre_identitario',
        ),
        migrations.RemoveField(
            model_name='reconocimientoidentidad',
            name='nombre_legal',
        ),
        migrations.RemoveField(
            model_name='reconocimientoidentidad',
            name='pronombres',
        ),
        migrations.RemoveField(
            model_name='reconocimientoidentidad',
            name='rut_estudiante',
        ),
        migrations.AddField(
            model_name='reconocimientoidentidad',
            name='apoderado_apellidos',
            field=models.CharField(blank=True, max_length=100, verbose_name='Apellidos'),
        ),
        migrations.AddField(
            model_name='reconocimientoidentidad',
            name='apoderado_celular',
            field=models.CharField(blank=True, max_length=15, verbose_name='Celular'),
        ),
        migrations.AddField(
            model_name='reconocimientoidentidad',
            name='apoderado_domicilio',
            field=models.CharField(blank=True, max_length=200, verbose_name='Domicilio'),
        ),
        migrations.AddField(
            model_name='reconocimientoidentidad',
            name='apoderado_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Correo'),
        ),
        migrations.AddField(
            model_name='reconocimientoidentidad',
            name='apoderado_nombres',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nombres'),
        ),
        migrations.AddField(
            model_name='reconocimientoidentidad',
            name='apoderado_run',
            field=models.CharField(blank=True, max_length=12, verbose_name='RUT'),
        ),
        migrations.AddField(
            model_name='reconocimientoidentidad',
            name='estudiante_apellidos',
            field=models.CharField(blank=True, max_length=200, verbose_name='Apellidos'),
        ),
        migrations.AddField(
            model_name='reconocimientoidentidad',
            name='estudiante_curso',
            field=models.CharField(blank=True, max_length=10, verbose_name='Curso'),
        ),
        migrations.AddField(
            model_name='reconocimientoidentidad',
            name='estudiante_domicilio',
            field=models.CharField(blank=True, max_length=200, verbose_name='Domicilio'),
        ),
        migrations.AddField(
            model_name='reconocimientoidentidad',
            name='estudiante_edad',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Edad'),
        ),
        migrations.AddField(
            model_name='reconocimientoidentidad',
            name='estudiante_fecha_nacimiento',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha nacimiento'),
        ),
        migrations.AddField(
            model_name='reconocimientoidentidad',
            name='estudiante_nombre_legal',
            field=models.CharField(blank=True, max_length=200, verbose_name='Nombre Legal'),
        ),
        migrations.AddField(
            model_name='reconocimientoidentidad',
            name='estudiante_nombre_social',
            field=models.CharField(blank=True, max_length=200, verbose_name='Nombre Social'),
        ),
        migrations.AddField(
            model_name='reconocimientoidentidad',
            name='estudiante_run',
            field=models.CharField(blank=True, max_length=12, verbose_name='RUT'),
        ),
        migrations.AddField(
            model_name='reconocimientoidentidad',
            name='firma_apoderado',
            field=models.CharField(blank=True, max_length=200, verbose_name='Firma apoderado'),
        ),
        migrations.AddField(
            model_name='reconocimientoidentidad',
            name='firma_estudiante',
            field=models.CharField(blank=True, max_length=200, verbose_name='Firma estudiante'),
        ),
        migrations.AddField(
            model_name='reconocimientoidentidad',
            name='medida_libro_clases',
            field=models.BooleanField(null=True, verbose_name='Agregar en el libro de clases el nombre social...'),
        ),
        migrations.AddField(
            model_name='reconocimientoidentidad',
            name='medida_servicios_higienicos',
            field=models.BooleanField(null=True, verbose_name='Utilización de servicios higiénicos...'),
        ),
        migrations.AddField(
            model_name='reconocimientoidentidad',
            name='medida_uniforme',
            field=models.BooleanField(null=True, verbose_name='Utilización de uniforme, ropa deportiva y/o accesorios...'),
        ),
        migrations.AddField(
            model_name='reconocimientoidentidad',
            name='medida_uso_nombre_social',
            field=models.BooleanField(null=True, verbose_name='Uso del nombre social en todos los espacios educativos'),
        ),
        migrations.DeleteModel(
            name='GestionReconocimiento',
        ),
    ]
