# Generated by Django 4.2.25 on 2025-11-04 02:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('protocolos', '0012_auto_20251028_1940'),
        ('formularios', '0009_alter_reconocimientoidentidad_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActaReunionIdentidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_reunion', models.DateField(blank=True, null=True, verbose_name='Fecha')),
                ('acuerdo_nombre_social', models.TextField(blank=True, verbose_name='Acuerdos alcanzados')),
                ('fecha_impl_nombre_social', models.DateField(blank=True, null=True, verbose_name='Fecha de implementación (si corresponde)')),
                ('acuerdo_libro_clases', models.TextField(blank=True, verbose_name='Acuerdos alcanzados')),
                ('fecha_impl_libro_clases', models.DateField(blank=True, null=True, verbose_name='Fecha de implementación (si corresponde)')),
                ('acuerdo_uniforme', models.TextField(blank=True, verbose_name='Acuerdos alcanzados')),
                ('fecha_impl_uniforme', models.DateField(blank=True, null=True, verbose_name='Fecha de implementación (si corresponde)')),
                ('acuerdo_servicios_higienicos', models.TextField(blank=True, verbose_name='Acuerdos alcanzados')),
                ('fecha_impl_servicios_higienicos', models.DateField(blank=True, null=True, verbose_name='Fecha de implementación (si corresponde)')),
                ('declaracion_participa_programas', models.BooleanField(null=True, verbose_name='¿Están participando de algunos de los programas del artículo 23...?')),
                ('declaracion_info_adicional', models.TextField(blank=True, verbose_name='Si la respuesta es Sí, proporcione número, correo y nombre/institución a cargo')),
                ('firma_apoderado', models.CharField(blank=True, max_length=200, verbose_name='Firma padre, madre, tutor y/o apoderado')),
                ('firma_estudiante', models.CharField(blank=True, max_length=200, verbose_name='Estudiante')),
                ('firma_rector', models.CharField(blank=True, max_length=200, verbose_name='Rector(a)')),
                ('protocolo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='acta_reunion_identidad', to='protocolos.protocolo')),
            ],
        ),
    ]
