# Generated by Django 5.2.8 on 2025-11-11 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formularios', '0009_estudiantemadrepadreficha0_estudiantemadrepadreficha1_estudiantemadrepadreficha2'),
        ('formularios', '0010_actareunionidentidad'),
    ]

    operations = [
    ]
