# Generated by Django 5.2.7 on 2025-11-10 21:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formularios', '0011_merge_20251110_1817'),
        ('protocolos', '0012_auto_20251028_1940'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalidaPedagogicaAnexo1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('establecimiento_nombre', models.CharField(blank=True, max_length=255, verbose_name='Nombre Establecimiento')),
                ('establecimiento_rbd', models.CharField(blank=True, max_length=100, verbose_name='RBD')),
                ('establecimiento_direccion', models.CharField(blank=True, max_length=255, verbose_name='Dirección')),
                ('establecimiento_fono', models.CharField(blank=True, max_length=100, verbose_name='Fono')),
                ('rector_nombre', models.CharField(blank=True, max_length=255, verbose_name='Nombre Rector')),
                ('rector_run', models.CharField(blank=True, max_length=20, verbose_name='RUN Rector')),
                ('rector_correo', models.EmailField(blank=True, max_length=254, verbose_name='Correo Electrónico Rector')),
                ('rector_fono', models.CharField(blank=True, max_length=100, verbose_name='Fono Rector')),
                ('docente_nombre', models.CharField(max_length=255, verbose_name='Nombre Docente Responsable')),
                ('docente_run', models.CharField(max_length=20, verbose_name='RUN Docente')),
                ('docente_correo', models.EmailField(max_length=254, verbose_name='Correo Electrónico Docente')),
                ('docente_fono', models.CharField(max_length=100, verbose_name='Fono Docente')),
                ('actividad_nombre', models.CharField(max_length=255, verbose_name='Nombre Actividad')),
                ('actividad_fecha_hora', models.DateTimeField(blank=True, null=True, verbose_name='Fecha y Hora de la Actividad')),
                ('actividad_niveles_cursos_participantes', models.CharField(max_length=500, verbose_name='Niveles y/o Cursos Participantes')),
                ('listado_estudiantes', models.TextField(blank=True, verbose_name='Listado Estudiantes (Nombre, Curso, Fono Apoderado)')),
                ('listado_docentes', models.TextField(blank=True, verbose_name='Listado Docentes (Nombre, Asignatura, Fono)')),
                ('listado_apoderados', models.TextField(blank=True, verbose_name='Listado Apoderados (Nombre, Curso, Fono)')),
                ('cursos_sin_profesor', models.TextField(blank=True, verbose_name='Cursos sin profesor (Curso, Día, Hora, Reemplaza)')),
                ('profesores_con_clases', models.TextField(blank=True, verbose_name='Profesores que tienen clases con cursos que asisten')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('protocolo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='salida_pedagogica_anexo1', to='protocolos.protocolo')),
            ],
            options={
                'verbose_name': 'Anexo 1: Ficha Salida Pedagógica',
            },
        ),
    ]
