# Generated by Django 5.2.7 on 2025-11-11 20:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formularios', '0012_salidapedagogicaanexo1'),
        ('protocolos', '0012_auto_20251028_1940'),
    ]

    operations = [
        migrations.CreateModel(
            name='DesregulacionEmocional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_estudiante', models.CharField(max_length=200, verbose_name='Nombre del estudiante')),
                ('curso', models.CharField(max_length=100, verbose_name='Curso')),
                ('profesor_jefe', models.CharField(max_length=200, verbose_name='Profesor (a) jefe')),
                ('profesora_diferencial', models.CharField(blank=True, max_length=200, null=True, verbose_name='Profesora diferencial')),
                ('lugar_desregulacion', models.CharField(max_length=255, verbose_name='Lugar donde se produce la desregulación')),
                ('fecha_hora', models.DateTimeField(verbose_name='Fecha y Hora')),
                ('descripcion_situacion', models.TextField(verbose_name='Descripción de la situación')),
                ('nombre_firma_funcionario', models.CharField(max_length=200, verbose_name='Nombre y firma de funcionario/a')),
                ('nombre_firma_2', models.CharField(help_text='Segunda firma', max_length=200, verbose_name='Nombre y firma')),
                ('etapa1_actividad_realizada', models.BooleanField(default=False)),
                ('etapa1_tematica_realizada', models.BooleanField(default=False)),
                ('etapa1_contencion_sala_realizada', models.BooleanField(default=False)),
                ('etapa1_saca_sala_realizada', models.BooleanField(default=False)),
                ('etapa1_silencio_realizada', models.BooleanField(default=False)),
                ('etapa1_otros_realizada', models.BooleanField(default=False)),
                ('etapa1_otros_descripcion', models.CharField(blank=True, max_length=255, verbose_name='Otros (especificar)')),
                ('etapa1_responsables_generales', models.TextField(blank=True, verbose_name='Responsable(s) de Etapa 1')),
                ('etapa2_retiran_elementos_realizada', models.BooleanField(default=False)),
                ('etapa2_reducen_estimulos_realizada', models.BooleanField(default=False)),
                ('etapa2_evitan_aglomeraciones_realizada', models.BooleanField(default=False)),
                ('etapa2_permite_lugar_agrado_realizada', models.BooleanField(default=False)),
                ('etapa2_fomenta_dialogo_realizada', models.BooleanField(default=False)),
                ('etapa2_concede_descanso_realizada', models.BooleanField(default=False)),
                ('etapa2_otros_realizada', models.BooleanField(default=False)),
                ('etapa2_otros_descripcion', models.CharField(blank=True, max_length=255, verbose_name='Otros (especificar) Etapa 2')),
                ('etapa2_responsables_generales', models.TextField(blank=True, verbose_name='Responsable(s) de Etapa 2')),
                ('etapa3_traslada_curso_realizada', models.BooleanField(default=False)),
                ('etapa3_restriccion_movimiento_realizada', models.BooleanField(default=False)),
                ('etapa3_llama_apoderado_realizada', models.BooleanField(default=False)),
                ('etapa3_otros_realizada', models.BooleanField(default=False)),
                ('etapa3_otros_descripcion', models.CharField(blank=True, max_length=255, verbose_name='Otros (especificar) Etapa 3')),
                ('etapa3_responsables_generales', models.TextField(blank=True, verbose_name='Responsable(s) de Etapa 3')),
                ('protocolo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='desregulacion_emocional', to='protocolos.protocolo')),
            ],
            options={
                'verbose_name': 'Bitácora Desregulación Emocional (DEC)',
                'verbose_name_plural': 'Bitácoras Desregulación Emocional (DEC)',
            },
        ),
    ]
