# Generated by Django 5.2.7 on 2025-11-12 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formularios', '0013_desregulacionemocional'),
        ('protocolos', '0012_auto_20251028_1940'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediacionActaFinal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_acta', models.DateField(blank=True, null=True, verbose_name='Fecha del Acta')),
                ('partes_individualizadas', models.TextField(blank=True, help_text='Ej: Solicitante (Nombre, RUT) y Solicitado (Nombre, RUT)', verbose_name='Individualización de las partes')),
                ('acuerdo_logrado', models.BooleanField(null=True, verbose_name='¿Se logró un acuerdo (Conciliación/Mediación)?')),
                ('acuerdo_1_objetivo', models.CharField(blank=True, max_length=255, verbose_name='Acuerdo 1: Objetivo')),
                ('acuerdo_1_actividades', models.TextField(blank=True, verbose_name='Acuerdo 1: Actividades')),
                ('acuerdo_1_responsable', models.CharField(blank=True, max_length=255, verbose_name='Acuerdo 1: Responsable')),
                ('acuerdo_1_verificacion', models.CharField(blank=True, max_length=255, verbose_name='Acuerdo 1: Medio de Verificación')),
                ('acuerdo_1_plazos', models.CharField(blank=True, max_length=255, verbose_name='Acuerdo 1: Plazos')),
                ('acuerdo_2_objetivo', models.CharField(blank=True, max_length=255, verbose_name='Acuerdo 2: Objetivo')),
                ('acuerdo_2_actividades', models.TextField(blank=True, verbose_name='Acuerdo 2: Actividades')),
                ('acuerdo_2_responsable', models.CharField(blank=True, max_length=255, verbose_name='Acuerdo 2: Responsable')),
                ('acuerdo_2_verificacion', models.CharField(blank=True, max_length=255, verbose_name='Acuerdo 2: Medio de Verificación')),
                ('acuerdo_2_plazos', models.CharField(blank=True, max_length=255, verbose_name='Acuerdo 2: Plazos')),
                ('acuerdo_3_objetivo', models.CharField(blank=True, max_length=255, verbose_name='Acuerdo 3: Objetivo')),
                ('acuerdo_3_actividades', models.TextField(blank=True, verbose_name='Acuerdo 3: Actividades')),
                ('acuerdo_3_responsable', models.CharField(blank=True, max_length=255, verbose_name='Acuerdo 3: Responsable')),
                ('acuerdo_3_verificacion', models.CharField(blank=True, max_length=255, verbose_name='Acuerdo 3: Medio de Verificación')),
                ('acuerdo_3_plazos', models.CharField(blank=True, max_length=255, verbose_name='Acuerdo 3: Plazos')),
                ('motivo_frustrado', models.TextField(blank=True, help_text='Detalle por qué no se alcanzaron acuerdos [cite: 4195]', verbose_name='Motivo del Acta Frustrada')),
                ('firma_conciliador', models.CharField(blank=True, max_length=255, verbose_name='Nombre y Firma Conciliador/Mediador')),
                ('firma_parte_1', models.CharField(blank=True, max_length=255, verbose_name='Nombre y Firma Parte 1 (Solicitante)')),
                ('firma_parte_2', models.CharField(blank=True, max_length=255, verbose_name='Nombre y Firma Parte 2 (Solicitado)')),
                ('protocolo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mediacion_acta_final', to='protocolos.protocolo')),
            ],
        ),
        migrations.CreateModel(
            name='MediacionInformacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solicitado_nombre', models.CharField(blank=True, max_length=255, verbose_name='Nombre Completo Solicitado')),
                ('solicitado_run', models.CharField(blank=True, max_length=12, verbose_name='RUN Solicitado')),
                ('solicitado_telefono', models.CharField(blank=True, max_length=20, verbose_name='Teléfono Solicitado')),
                ('solicitado_domicilio', models.CharField(blank=True, max_length=255, verbose_name='Domicilio Solicitado')),
                ('solicitado_correo', models.EmailField(blank=True, max_length=254, verbose_name='Correo Electrónico Solicitado')),
                ('info_nombre_solicitante', models.BooleanField(null=True, verbose_name='Se informó Nombre Solicitante')),
                ('info_motivo', models.BooleanField(null=True, verbose_name='Se informó Motivo de Mediación')),
                ('info_fecha_hora', models.BooleanField(null=True, verbose_name='Se informó Fecha y Hora')),
                ('info_fecha_hora_detalle', models.CharField(blank=True, max_length=100, verbose_name='Fecha y Hora informada')),
                ('info_voluntario', models.BooleanField(null=True, verbose_name='Se señaló que el proceso es voluntario')),
                ('respuesta_solicitado', models.CharField(blank=True, choices=[('Acepta', 'Acepta participar'), ('Rechaza', 'No desea participar'), ('No Responde', 'No da respuesta en el plazo')], max_length=50, verbose_name='Respuesta del Solicitado')),
                ('medio_informado', models.CharField(blank=True, choices=[('Telefono', 'Teléfono'), ('Correo', 'Correo Electrónico'), ('Carta', 'Carta Certificada'), ('Agenda', 'Agenda Escolar'), ('Otro', 'Otro')], max_length=50, verbose_name='Medio por el cual se le informó')),
                ('verificacion_detalle', models.TextField(blank=True, verbose_name='Detalle de la verificación (Ej: Teléfono, fecha, hora, funcionario)')),
                ('protocolo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mediacion_informacion', to='protocolos.protocolo')),
            ],
        ),
        migrations.CreateModel(
            name='MediacionSolicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solicitante_nombre', models.CharField(blank=True, max_length=255, verbose_name='Nombre Completo Solicitante')),
                ('solicitante_run', models.CharField(blank=True, max_length=12, verbose_name='RUN Solicitante')),
                ('solicitante_telefono', models.CharField(blank=True, max_length=20, verbose_name='Teléfono Solicitante')),
                ('solicitante_domicilio', models.CharField(blank=True, max_length=255, verbose_name='Domicilio Solicitante')),
                ('solicitante_correo', models.EmailField(blank=True, max_length=254, verbose_name='Correo Electrónico Solicitante')),
                ('estudiante_nombre', models.CharField(blank=True, max_length=255, verbose_name='Nombre Completo Estudiante')),
                ('estudiante_curso', models.CharField(blank=True, max_length=100, verbose_name='Curso Estudiante')),
                ('estudiante_run', models.CharField(blank=True, max_length=12, verbose_name='RUN Estudiante')),
                ('estudiante_domicilio', models.CharField(blank=True, max_length=255, verbose_name='Domicilio Estudiante')),
                ('solicitado_nombre', models.CharField(blank=True, max_length=255, verbose_name='Nombre Solicitado')),
                ('solicitado_rol', models.CharField(blank=True, choices=[('Estudiante', 'Estudiante'), ('Apoderado', 'Apoderado'), ('Docente', 'Docente'), ('Profesor Jefe', 'Profesor Jefe'), ('Profesor de Asignatura', 'Profesor de Asignatura'), ('Asistente', 'Asistente'), ('Otro', 'Otro')], max_length=100, verbose_name='Rol del Solicitado')),
                ('solicitado_curso_cargo', models.CharField(blank=True, help_text='Curso (si es estudiante/apoderado/prof. jefe) o Cargo (si es asistente/otro)', max_length=255, verbose_name='Curso / Cargo')),
                ('motivo_solicitud', models.TextField(blank=True, verbose_name='Motivo de la Solicitud')),
                ('antecedentes', models.TextField(blank=True, verbose_name='Antecedentes que estime necesarios')),
                ('protocolo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mediacion_solicitud', to='protocolos.protocolo')),
            ],
        ),
    ]
