# Generated by Django 5.2.8 on 2025-11-12 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formularios', '0011_merge_20251111_1839'),
        ('formularios', '0014_mediacionactafinal_mediacioninformacion_and_more'),
    ]

    operations = [
    ]
