# Generated by Django 5.2.7 on 2025-11-19 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formularios', '0015_merge_20251112_1711'),
        ('protocolos', '0012_auto_20251028_1940'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvidenciaExtra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('fecha', models.DateField()),
                ('descripcion', models.TextField(blank=True)),
                ('archivo', models.FileField(upload_to='evidencias_extra/')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('protocolo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidencias_extra', to='protocolos.protocolo')),
            ],
            options={
                'db_table': 'protocolo1_evidenciaextra',
                'ordering': ['-creado_en'],
            },
        ),
    ]
